dataset: mnist
layer: s4
seed: 0

model:
  d_model: 128
  n_layers: 4
  dropout: 0.0
  prenorm: True
  embedding: False
  layer:
    N: 64

train: 
  epochs: 2
  batch_size: 128
  lr: 0.001
  lr_schedule: False
  weight_decay: 0.01
  checkpoint: True
  suffix: null
  sample: null
